# Generated by Django 5.0.4 on 2024-04-10 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Compras', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
